# Generated by Django 5.1 on 2024-08-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_avatar_user_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Токен"
            ),
        ),
    ]
