# Generated by Django 5.1 on 2024-08-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(default="-", max_length=10, verbose_name="Токен"),
        ),
    ]
