# Generated by Django 5.1 on 2024-08-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_advertisement_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
    ]
